---

- hosts: all
  gather_facts: False
  become: yes
  become_user: root
  any_errors_fatal: true
  roles:
     - install_packages
     - setup_app
     - configure_nginx_uwsgi
     - reload_services
