---

- name: Create nginx config
  template:
    src: templates/nginx-host.conf.j2
    dest: '{{ nginx_dir }}/{{ app_name }}.conf'
    owner: root
    group: root
    mode: 0644

- name: Create uWSGI config
  template:
    src: templates/uwsgi-vassal.ini.j2
    dest: '{{ uwsgi_dir }}/{{ app_name }}.ini'
    owner: '{{ uid }}'
    group: uwsgi
    mode: 0644
